/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.math.BigDecimal;
import java.math.MathContext;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mb
 */
public class Balances extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    DecimalFormat d = new DecimalFormat("####.##");
    Locale region = Locale.getDefault();
    NumberFormat formato = NumberFormat.getCurrencyInstance(region);
    NumberFormat format = NumberFormat.getCurrencyInstance();

    /**
     * Creates new form Inventario
     */
    public Balances() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(590, 295);
        Date date = new Date();
        jDateChooser_desde.setDate(date);
        jDateChooser_hasta.setDate(date);
        prueba();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jDateChooser_desde = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser_hasta = new com.toedter.calendar.JDateChooser();
        jButton_aplicar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_compras = new javax.swing.JLabel();
        jLabel_ventas = new javax.swing.JLabel();
        jLabel_balance = new javax.swing.JLabel();
        jLabel_WallpaperHeader = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ventas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 20));

        jDateChooser_desde.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Compras: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        jDateChooser_hasta.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 150, -1));

        jButton_aplicar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_aplicar.setText("Aplicar");
        jButton_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aplicarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_aplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Balance:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Desde:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Hasta:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 40));

        jLabel_compras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_compras.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel_compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 130, 20));

        jLabel_ventas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_ventas.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, 20));

        jLabel_balance.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_balance.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 130, 20));

        jLabel_WallpaperHeader.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_WallpaperHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_WallpaperHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_WallpaperHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_WallpaperHeader.setText("     Balances");
        jLabel_WallpaperHeader.setOpaque(true);
        getContentPane().add(jLabel_WallpaperHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 60));

        jLabel_Wallpaper.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Wallpaper.setOpaque(true);
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aplicarActionPerformed
        jDateChooser_desde.getDate();
        jDateChooser_hasta.getDate();

        if (jDateChooser_desde.getDate().after(jDateChooser_hasta.getDate())) {
            JOptionPane.showMessageDialog(null, "Error, fechas invalidas");
        } else {
            prueba();
        }
    }//GEN-LAST:event_jButton_aplicarActionPerformed

    public void prueba() {

        try {
            Connection cn = Conexion.conectar();

            String entradas = null;
            String salidas = null;
            BigDecimal entradas_importe_total = null;
            BigDecimal salidas_importe_total = null;

            entradas = "SELECT SUM(ed.importe_total) FROM entradas ed WHERE ed.fecha >= ? AND ed.fecha <= ?";
            salidas = "SELECT SUM(sd.importe_total) FROM salidas sd WHERE sd.fecha >= ? AND sd.fecha <= ?";

            PreparedStatement pst1 = cn.prepareStatement(entradas);
            pst1.setDate(1, new java.sql.Date(jDateChooser_desde.getDate().getTime()));
            pst1.setDate(2, new java.sql.Date(jDateChooser_hasta.getDate().getTime()));
            ResultSet rs1 = pst1.executeQuery();

            if (rs1.next()) {
                entradas_importe_total = (BigDecimal) rs1.getObject(1);
                PreparedStatement pst2 = cn.prepareStatement(salidas);
                pst2.setDate(1, new java.sql.Date(jDateChooser_desde.getDate().getTime()));
                pst2.setDate(2, new java.sql.Date(jDateChooser_hasta.getDate().getTime()));
                ResultSet rs2 = pst2.executeQuery();

                if (rs2.next()) {
                    salidas_importe_total = (BigDecimal) rs2.getObject(1);
                    if (salidas_importe_total != null && entradas_importe_total != null) {
                        BigDecimal total = salidas_importe_total.subtract(entradas_importe_total);
                        jLabel_compras.setText(formato.format(entradas_importe_total));
                        jLabel_ventas.setText(formato.format(salidas_importe_total));
                        if (total.compareTo(BigDecimal.ZERO) > 0) {
                            jLabel_balance.setText(formato.format(total) + " +");
                        } else if (total.compareTo(BigDecimal.ZERO) < 0) {
                            jLabel_balance.setText(formato.format(total) + " -");
                        } else {
                            jLabel_balance.setText(formato.format(total));
                        }
                        
                    }
                }

            }

            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al llenar tabla." + e);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion, contacte al administrador");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Balances().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aplicar;
    private com.toedter.calendar.JDateChooser jDateChooser_desde;
    private com.toedter.calendar.JDateChooser jDateChooser_hasta;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_WallpaperHeader;
    private javax.swing.JLabel jLabel_balance;
    private javax.swing.JLabel jLabel_compras;
    private javax.swing.JLabel jLabel_ventas;
    // End of variables declaration//GEN-END:variables
}
