/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author mb
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
        setResizable(false);
        setTitle("Kiosco 24");
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_fondoTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_ventas = new javax.swing.JButton();
        jButton_ingresos = new javax.swing.JButton();
        jButton_proveedores = new javax.swing.JButton();
        jButton_inventario = new javax.swing.JButton();
        jButton_productos = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_fondoTitulo.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_fondoTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_fondoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fondoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_fondoTitulo.setText("ZONA CENTRO");
        jLabel_fondoTitulo.setOpaque(true);
        getContentPane().add(jLabel_fondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Proveedores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Balances");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ventas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Productos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 80, -1));

        jButton_ventas.setBackground(new java.awt.Color(255, 255, 255));
        jButton_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cash-80.png"))); // NOI18N
        jButton_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ventasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 130));

        jButton_ingresos.setBackground(new java.awt.Color(255, 255, 255));
        jButton_ingresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-shopping-cart-80.png"))); // NOI18N
        jButton_ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ingresosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 130, 130));

        jButton_proveedores.setBackground(new java.awt.Color(255, 255, 255));
        jButton_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-supplier-64.png"))); // NOI18N
        jButton_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_proveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 130, 130));

        jButton_inventario.setBackground(new java.awt.Color(255, 255, 255));
        jButton_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-statistics-50.png"))); // NOI18N
        jButton_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 130, 130));

        jButton_productos.setBackground(new java.awt.Color(255, 255, 255));
        jButton_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-fast-moving-consumer-goods-50.png"))); // NOI18N
        jButton_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_productosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 130, 130));

        jLabel_Wallpaper.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Wallpaper.setOpaque(true);
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_proveedoresActionPerformed
        Proveedores proveedores = new Proveedores();
        proveedores.setVisible(true);
    }//GEN-LAST:event_jButton_proveedoresActionPerformed

    private void jButton_ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ingresosActionPerformed
        Entradas entradas = new Entradas();
        entradas.setVisible(true);
    }//GEN-LAST:event_jButton_ingresosActionPerformed

    private void jButton_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inventarioActionPerformed
        Balances reportes = new Balances();
        reportes.setVisible(true);
    }//GEN-LAST:event_jButton_inventarioActionPerformed

    private void jButton_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ventasActionPerformed
        Salidas salidas = new Salidas();
        salidas.setVisible(true);
    }//GEN-LAST:event_jButton_ventasActionPerformed

    private void jButton_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_productosActionPerformed
        Productos productos = new Productos();
        productos.setVisible(true);
    }//GEN-LAST:event_jButton_productosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ingresos;
    private javax.swing.JButton jButton_inventario;
    private javax.swing.JButton jButton_productos;
    private javax.swing.JButton jButton_proveedores;
    private javax.swing.JButton jButton_ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_fondoTitulo;
    // End of variables declaration//GEN-END:variables
}
